// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { TabBarComponent } from './tab-bar.component';

@NgModule({
	imports: [CommonModule],
	declarations: [TabBarComponent],
	exports: [TabBarComponent]
})
export class ForgeTabBarModule {}