// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { TabBarComponent as TabBarComponentCustomElement, defineTabBarComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-tab-bar>` element. */
@Component({
  selector: 'forge-tab-bar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class TabBarComponent {

	/** Gets and sets the active tab index. */
	@Input()
	public set activeTab(value: TabBarComponentCustomElement['activeTab'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.activeTab = +value;
		});
	}

	public get activeTab(): TabBarComponentCustomElement['activeTab'] {
		return this.elementRef.nativeElement.activeTab;
	}

	/** Gets/sets the layout mode that controls how the tabs are sized and rendered. */
	@Input()
	public set layoutMode(value: TabBarComponentCustomElement['layoutMode']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.layoutMode = value;
		});
	}

	public get layoutMode(): TabBarComponentCustomElement['layoutMode'] {
		return this.elementRef.nativeElement.layoutMode;
	}

	/** Gets/sets the layout alignment. Only pertains to non-full width layout modes. */
	@Input()
	public set layoutAlign(value: TabBarComponentCustomElement['layoutAlign']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.layoutAlign = value;
		});
	}

	public get layoutAlign(): TabBarComponentCustomElement['layoutAlign'] {
		return this.elementRef.nativeElement.layoutAlign;
	}

	/** Gets/sets whether the component displays an underline or not. Default is `false`. */
	@Input()
	public set underline(value: TabBarComponentCustomElement['underline'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.underline = value != null && `${value}` !== 'false';
		});
	}

	public get underline(): TabBarComponentCustomElement['underline'] {
		return this.elementRef.nativeElement.underline;
	}

	/** Gets/sets whether tabs are auto-activated when using arrow keys. Default is `true` */
	@Input()
	public set autoActivate(value: TabBarComponentCustomElement['autoActivate'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.autoActivate = value != null && `${value}` !== 'false';
		});
	}

	public get autoActivate(): TabBarComponentCustomElement['autoActivate'] {
		return this.elementRef.nativeElement.autoActivate;
	}

	/** Gets/sets whether the tabs are displayed with as their stacked variant. Default is `false`. */
	@Input()
	public set stacked(value: TabBarComponentCustomElement['stacked'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.stacked = value != null && `${value}` !== 'false';
		});
	}

	public get stacked(): TabBarComponentCustomElement['stacked'] {
		return this.elementRef.nativeElement.stacked;
	}

	/** Gets/sets whether the scroll buttons can be displayed or not. Default is `true`. The component handles visibility automatically. */
	@Input()
	public set scrollButtons(value: TabBarComponentCustomElement['scrollButtons'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.scrollButtons = value != null && `${value}` !== 'false';
		});
	}

	public get scrollButtons(): TabBarComponentCustomElement['scrollButtons'] {
		return this.elementRef.nativeElement.scrollButtons;
	}

	/** Gets/sets whether the scroll buttons are visible indefinitely or not. Default is `false`. */
	@Input()
	public set forceScrollButtons(value: TabBarComponentCustomElement['forceScrollButtons'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.forceScrollButtons = value != null && `${value}` !== 'false';
		});
	}

	public get forceScrollButtons(): TabBarComponentCustomElement['forceScrollButtons'] {
		return this.elementRef.nativeElement.forceScrollButtons;
	}

	/** Activates the tab at the given index. */
	public activateTab(...args: Parameters<TabBarComponentCustomElement['activateTab']>): ReturnType<TabBarComponentCustomElement['activateTab']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.activateTab(...args));
	}

	/** Scrolls the tab at the given index into view. */
	public scrollTabIntoView(...args: Parameters<TabBarComponentCustomElement['scrollTabIntoView']>): ReturnType<TabBarComponentCustomElement['scrollTabIntoView']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.scrollTabIntoView(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<TabBarComponentCustomElement>,
		protected zone: NgZone
	) {
		defineTabBarComponent();
		changeDetectorRef.detach();
	}
}
