// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ViewComponent as ViewComponentCustomElement, defineViewComponent } from '@tylertech/forge';

/**  */
@Component({
    selector: 'forge-view',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: '<ng-content />',
    standalone: false
})
export class ViewComponent {
	protected elementRef = inject<ElementRef<ViewComponentCustomElement>>(ElementRef);
	protected zone = inject(NgZone);


	/** The forge-view element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	constructor() {
		const changeDetectorRef = inject(ChangeDetectorRef);

		defineViewComponent();
		changeDetectorRef.detach();
	}
}
