// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ViewComponent as ViewComponentCustomElement, defineViewComponent } from '@tylertech/forge';

/**  */
@Component({
    selector: 'forge-view',
    changeDetection: ChangeDetectionStrategy.OnPush,
    template: '<ng-content></ng-content>',
    standalone: false
})
export class ViewComponent {

	/** The forge-view element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ViewComponentCustomElement>,
		protected zone: NgZone
	) {
		defineViewComponent();
		changeDetectorRef.detach();
	}
}
