// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { InlineMessageComponent as InlineMessageComponentCustomElement, defineInlineMessageComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-inline-message>` custom element. */
@Component({
  selector: 'forge-inline-message',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class InlineMessageComponent {

	/** The forge-inline-message element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<InlineMessageComponentCustomElement>,
		protected zone: NgZone
	) {
		defineInlineMessageComponent();
		changeDetectorRef.detach();
	}
}
