// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { SelectDropdownComponent as SelectDropdownComponentCustomElement, defineSelectDropdownComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-select-dropdown>` custom element. */
@Component({
  selector: 'forge-select-dropdown',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class SelectDropdownComponent {

	/** Sets the target element CSS selector */
	@Input()
	public set target(value: SelectDropdownComponentCustomElement['target']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.target = value;
		});
	}

	public get target(): SelectDropdownComponentCustomElement['target'] {
		return this.elementRef.nativeElement.target;
	}

	/** Sets the selected text element CSS selector */
	@Input()
	public set selectedTextTarget(value: SelectDropdownComponentCustomElement['selectedTextTarget']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.selectedTextTarget = value;
		});
	}

	public get selectedTextTarget(): SelectDropdownComponentCustomElement['selectedTextTarget'] {
		return this.elementRef.nativeElement.selectedTextTarget;
	}

	/** Controls whether the selected text is synchronized to the target elements' text content. Default is false. */
	@Input()
	public set syncSelectedText(value: SelectDropdownComponentCustomElement['syncSelectedText'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.syncSelectedText = value != null && `${value}` !== 'false';
		});
	}

	public get syncSelectedText(): SelectDropdownComponentCustomElement['syncSelectedText'] {
		return this.elementRef.nativeElement.syncSelectedText;
	}

	/** Gets/sets the value. */
	@Input()
	public set value(value: SelectDropdownComponentCustomElement['value']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.value = value;
		});
	}

	public get value(): SelectDropdownComponentCustomElement['value'] {
		return this.elementRef.nativeElement.value;
	}

	/** Gets/sets the selected index. */
	@Input()
	public set selectedIndex(value: SelectDropdownComponentCustomElement['selectedIndex']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.selectedIndex = value;
		});
	}

	public get selectedIndex(): SelectDropdownComponentCustomElement['selectedIndex'] {
		return this.elementRef.nativeElement.selectedIndex;
	}

	/** Gets/sets the available options. */
	@Input()
	public set options(value: SelectDropdownComponentCustomElement['options']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.options = value;
		});
	}

	public get options(): SelectDropdownComponentCustomElement['options'] {
		return this.elementRef.nativeElement.options;
	}

	/** Gets/sets the multiple select state. */
	@Input()
	public set multiple(value: SelectDropdownComponentCustomElement['multiple'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.multiple = value != null && `${value}` !== 'false';
		});
	}

	public get multiple(): SelectDropdownComponentCustomElement['multiple'] {
		return this.elementRef.nativeElement.multiple;
	}

	/** Gets the open state of the dropdown. */
	@Input()
	public set open(value: SelectDropdownComponentCustomElement['open'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.open = value != null && `${value}` !== 'false';
		});
	}

	public get open(): SelectDropdownComponentCustomElement['open'] {
		return this.elementRef.nativeElement.open;
	}

	/** Sets the option builder callback that will be executed when building the option list in the dropdown. */
	@Input()
	public set optionBuilder(value: SelectDropdownComponentCustomElement['optionBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.optionBuilder = value;
		});
	}

	public get optionBuilder(): SelectDropdownComponentCustomElement['optionBuilder'] {
		return this.elementRef.nativeElement.optionBuilder;
	}

	/** Sets the selected text builder callback that will be executed when getting the selected text to display in the field. */
	@Input()
	public set selectedTextBuilder(value: SelectDropdownComponentCustomElement['selectedTextBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.selectedTextBuilder = value;
		});
	}

	public get selectedTextBuilder(): SelectDropdownComponentCustomElement['selectedTextBuilder'] {
		return this.elementRef.nativeElement.selectedTextBuilder;
	}

	/** Sets the callback to be executed when the user selects a value. */
	@Input()
	public set beforeValueChange(value: SelectDropdownComponentCustomElement['beforeValueChange']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.beforeValueChange = value;
		});
	}

	public get beforeValueChange(): SelectDropdownComponentCustomElement['beforeValueChange'] {
		return this.elementRef.nativeElement.beforeValueChange;
	}

	/** Gets the popup element (when the dropdown is open). */
	@Input()
	public set popupElement(value: SelectDropdownComponentCustomElement['popupElement']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.popupElement = value;
		});
	}

	public get popupElement(): SelectDropdownComponentCustomElement['popupElement'] {
		return this.elementRef.nativeElement.popupElement;
	}

	/** Gets/sets the list of classes to apply to the popup element. */
	@Input()
	public set popupClasses(value: SelectDropdownComponentCustomElement['popupClasses']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.popupClasses = value;
		});
	}

	public get popupClasses(): SelectDropdownComponentCustomElement['popupClasses'] {
		return this.elementRef.nativeElement.popupClasses;
	}

	/** Gets/sets the callback function for generating header content within the popup. */
	@Input()
	public set popupHeaderBuilder(value: SelectDropdownComponentCustomElement['popupHeaderBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.popupHeaderBuilder = value;
		});
	}

	public get popupHeaderBuilder(): SelectDropdownComponentCustomElement['popupHeaderBuilder'] {
		return this.elementRef.nativeElement.popupHeaderBuilder;
	}

	/** Gets/sets the callback function for generating header content within the popup. */
	@Input()
	public set popupFooterBuilder(value: SelectDropdownComponentCustomElement['popupFooterBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.popupFooterBuilder = value;
		});
	}

	public get popupFooterBuilder(): SelectDropdownComponentCustomElement['popupFooterBuilder'] {
		return this.elementRef.nativeElement.popupFooterBuilder;
	}

	/** Gets/sets whether the popup width is synchronized with the popup target width. */
	@Input()
	public set syncPopupWidth(value: SelectDropdownComponentCustomElement['syncPopupWidth'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.syncPopupWidth = value != null && `${value}` !== 'false';
		});
	}

	public get syncPopupWidth(): SelectDropdownComponentCustomElement['syncPopupWidth'] {
		return this.elementRef.nativeElement.syncPopupWidth;
	}

	/** Gets/sets the maximum number of options to display in the dropdown. */
	@Input()
	public set optionLimit(value: SelectDropdownComponentCustomElement['optionLimit'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.optionLimit = +value;
		});
	}

	public get optionLimit(): SelectDropdownComponentCustomElement['optionLimit'] {
		return this.elementRef.nativeElement.optionLimit;
	}

	/** Controls the observation of scroll events on the dropdown. */
	@Input()
	public set observeScroll(value: SelectDropdownComponentCustomElement['observeScroll'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.observeScroll = value != null && `${value}` !== 'false';
		});
	}

	public get observeScroll(): SelectDropdownComponentCustomElement['observeScroll'] {
		return this.elementRef.nativeElement.observeScroll;
	}

	/** The number of pixels from the bottom to trigger the scroll bottom event. Only applicable if `observeScroll` is true. */
	@Input()
	public set observeScrollThreshold(value: SelectDropdownComponentCustomElement['observeScrollThreshold'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.observeScrollThreshold = +value;
		});
	}

	public get observeScrollThreshold(): SelectDropdownComponentCustomElement['observeScrollThreshold'] {
		return this.elementRef.nativeElement.observeScrollThreshold;
	}

	/** Gets/sets whether the popup width will be constrained to a max width of the viewport width (default: `100vw`). */
	@Input()
	public set constrainPopupWidth(value: SelectDropdownComponentCustomElement['constrainPopupWidth'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.constrainPopupWidth = value != null && `${value}` !== 'false';
		});
	}

	public get constrainPopupWidth(): SelectDropdownComponentCustomElement['constrainPopupWidth'] {
		return this.elementRef.nativeElement.constrainPopupWidth;
	}

	/**
	 * Gets/sets whether the options will wrap their text or not.
	 * This only applies if `constrainPopupWidth` is `true`, if there is an explicit width set via CSS.
	 */
	@Input()
	public set wrapOptionText(value: SelectDropdownComponentCustomElement['wrapOptionText'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.wrapOptionText = value != null && `${value}` !== 'false';
		});
	}

	public get wrapOptionText(): SelectDropdownComponentCustomElement['wrapOptionText'] {
		return this.elementRef.nativeElement.wrapOptionText;
	}


	public appendOptions(...args: Parameters<SelectDropdownComponentCustomElement['appendOptions']>): ReturnType<SelectDropdownComponentCustomElement['appendOptions']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.appendOptions(...args));
	}


	public selectAll(...args: Parameters<SelectDropdownComponentCustomElement['selectAll']>): ReturnType<SelectDropdownComponentCustomElement['selectAll']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.selectAll(...args));
	}


	public deselectAll(...args: Parameters<SelectDropdownComponentCustomElement['deselectAll']>): ReturnType<SelectDropdownComponentCustomElement['deselectAll']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.deselectAll(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<SelectDropdownComponentCustomElement>,
		protected zone: NgZone
	) {
		defineSelectDropdownComponent();
		changeDetectorRef.detach();
	}
}
