// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ScaffoldComponent as ScaffoldComponentCustomElement, defineScaffoldComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-scaffold>` element. */
@Component({
  selector: 'forge-scaffold',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ScaffoldComponent {

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ScaffoldComponentCustomElement>,
		protected zone: NgZone
	) {
		defineScaffoldComponent();
		changeDetectorRef.detach();
	}
}
