// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ToolbarComponent as ToolbarComponentCustomElement, defineToolbarComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-toolbar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ToolbarComponent {

	/** The forge-toolbar element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Controls whether a bottom divider (default) or top divider (true) is used. */
	@Input({ transform: booleanAttribute })
	public set inverted(value: ToolbarComponentCustomElement['inverted']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.inverted = value;
		});
	}
	public get inverted(): ToolbarComponentCustomElement['inverted'] {
		return this.nativeElement.inverted;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ToolbarComponentCustomElement>,
		protected zone: NgZone
	) {
		defineToolbarComponent();
		changeDetectorRef.detach();
	}
}
