// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { SkeletonComponent as SkeletonComponentCustomElement, defineSkeletonComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-skeleton',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class SkeletonComponent {
	protected elementRef = inject<ElementRef<SkeletonComponentCustomElement>>(ElementRef);
	protected zone = inject(NgZone);

	/** The forge-skeleton element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	constructor() {
		defineSkeletonComponent();
		const changeDetectorRef = inject(ChangeDetectorRef);
		changeDetectorRef.detach();
	}
}
