// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ListComponent as ListComponentCustomElement, defineListComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ListComponent {

	/** The forge-list element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Whether the list has all static items or not. */
	@Input({ transform: booleanAttribute })
	public set static(value: ListComponentCustomElement['static']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.static = value;
		});
	}
	public get static(): ListComponentCustomElement['static'] {
		return this.nativeElement.static;
	}

	/** Whether the list has all non-interactive items or not. */
	@Input({ transform: booleanAttribute })
	public set nonInteractive(value: ListComponentCustomElement['nonInteractive']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.nonInteractive = value;
		});
	}
	public get nonInteractive(): ListComponentCustomElement['nonInteractive'] {
		return this.nativeElement.nonInteractive;
	}

	/** Whether the list items are disabled or not. */
	@Input({ transform: booleanAttribute })
	public set disabled(value: ListComponentCustomElement['disabled']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.disabled = value;
		});
	}
	public get disabled(): ListComponentCustomElement['disabled'] {
		return this.nativeElement.disabled;
	}

	/** Whether the list has all dense items or not. */
	@Input({ transform: booleanAttribute })
	public set dense(value: ListComponentCustomElement['dense']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.dense = value;
		});
	}
	public get dense(): ListComponentCustomElement['dense'] {
		return this.nativeElement.dense;
	}

	/** Whether the list items propagate click events or not. */
	@Input({ transform: booleanAttribute })
	public set propagateClick(value: ListComponentCustomElement['propagateClick']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.propagateClick = value;
		});
	}
	public get propagateClick(): ListComponentCustomElement['propagateClick'] {
		return this.nativeElement.propagateClick;
	}

	/** Whether the list items within this list are indented. Default is false. */
	@Input({ transform: booleanAttribute })
	public set indented(value: ListComponentCustomElement['indented']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.indented = value;
		});
	}
	public get indented(): ListComponentCustomElement['indented'] {
		return this.nativeElement.indented;
	}

	/** The selected list item value(s). */
	@Input()
	public set selectedValue(value: ListComponentCustomElement['selectedValue']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.selectedValue = value;
		});
	}
	public get selectedValue(): ListComponentCustomElement['selectedValue'] {
		return this.nativeElement.selectedValue;
	}

	/** Whether the list has all two-line items or not. */
	@Input({ transform: booleanAttribute })
	public set twoLine(value: ListComponentCustomElement['twoLine']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.twoLine = value;
		});
	}
	public get twoLine(): ListComponentCustomElement['twoLine'] {
		return this.nativeElement.twoLine;
	}

	/** Whether the list has all three-line items or not. */
	@Input({ transform: booleanAttribute })
	public set threeLine(value: ListComponentCustomElement['threeLine']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.threeLine = value;
		});
	}
	public get threeLine(): ListComponentCustomElement['threeLine'] {
		return this.nativeElement.threeLine;
	}

	/** Whether the list has all items that wrap their text or not. */
	@Input({ transform: booleanAttribute })
	public set wrap(value: ListComponentCustomElement['wrap']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.wrap = value;
		});
	}
	public get wrap(): ListComponentCustomElement['wrap'] {
		return this.nativeElement.wrap;
	}

	/** The role of the list. Default is 'list'. Valid values are 'list', 'listbox', and 'menu'. */
	@Input()
	public set role(value: ListComponentCustomElement['role']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.role = value;
		});
	}
	public get role(): ListComponentCustomElement['role'] {
		return this.nativeElement.role;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ListComponentCustomElement>,
		protected zone: NgZone
	) {
		defineListComponent();
		changeDetectorRef.detach();
	}
}
