// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ListComponent as ListComponentCustomElement, defineListComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-list>` element. */
@Component({
  selector: 'forge-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ListComponent {

	/** The forge-list element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Gets/sets whether the list has all static items or not. */
	@Input({ transform: booleanAttribute })
	public set static(value: ListComponentCustomElement['static']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.static = value;
		});
	}
	public get static(): ListComponentCustomElement['static'] {
		return this.nativeElement.static;
	}

	/** Gets/sets whether the list has all dense items or not. */
	@Input({ transform: booleanAttribute })
	public set dense(value: ListComponentCustomElement['dense']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.dense = value;
		});
	}
	public get dense(): ListComponentCustomElement['dense'] {
		return this.nativeElement.dense;
	}

	/** Gets/sets whether the list items allow mousedown events through to their underlying list item elements. Default is true. */
	@Input({ transform: booleanAttribute })
	public set propagateClick(value: ListComponentCustomElement['propagateClick']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.propagateClick = value;
		});
	}
	public get propagateClick(): ListComponentCustomElement['propagateClick'] {
		return this.nativeElement.propagateClick;
	}

	/** Gets/sets whether the list items within this list are indented. Default is false. */
	@Input({ transform: booleanAttribute })
	public set indented(value: ListComponentCustomElement['indented']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.indented = value;
		});
	}
	public get indented(): ListComponentCustomElement['indented'] {
		return this.nativeElement.indented;
	}

	/** Gets/sets the selected list item value(s) */
	@Input()
	public set selectedValue(value: ListComponentCustomElement['selectedValue']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.selectedValue = value;
		});
	}
	public get selectedValue(): ListComponentCustomElement['selectedValue'] {
		return this.nativeElement.selectedValue;
	}


	public initializedCallback(...args: Parameters<ListComponentCustomElement['initializedCallback']>): ReturnType<ListComponentCustomElement['initializedCallback']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.initializedCallback(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ListComponentCustomElement>,
		protected zone: NgZone
	) {
		defineListComponent();
		changeDetectorRef.detach();
	}
}
