// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ForgeOpenIconModule } from '../open-icon';
import { ExpansionPanelComponent } from './expansion-panel.component';

@NgModule({
	imports: [CommonModule, ForgeOpenIconModule],
	declarations: [ExpansionPanelComponent],
	exports: [ExpansionPanelComponent, ForgeOpenIconModule]
})
export class ForgeExpansionPanelModule {}