// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core'; 
import { definePopupComponent } from '@tylertech/forge';

import { PopupComponent } from './popup.component';

@NgModule({
	imports: [CommonModule],
	declarations: [PopupComponent],
	exports: [PopupComponent]
})
export class ForgePopupProxyModule {
	constructor() {
		definePopupComponent();
	}
}