// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ListItemComponent } from './list-item.component';

@NgModule({
	imports: [CommonModule],
	declarations: [ListItemComponent],
	exports: [ListItemComponent]
})
export class ForgeListItemModule {}