// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { DialogComponent as DialogComponentCustomElement, defineDialogComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-dialog>` custom element. */
@Component({
  selector: 'forge-dialog',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class DialogComponent {

	/** The forge-dialog element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Controls whether clicking the backdrop closes the dialog or not. Default is true. */
	@Input({ transform: booleanAttribute })
	public set backdropClose(value: DialogComponentCustomElement['backdropClose']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.backdropClose = value;
		});
	}
	public get backdropClose(): DialogComponentCustomElement['backdropClose'] {
		return this.nativeElement.backdropClose;
	}

	/** Controls whether pressing the escape key closes the dialog or not. Default is true. */
	@Input({ transform: booleanAttribute })
	public set escapeClose(value: DialogComponentCustomElement['escapeClose']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.escapeClose = value;
		});
	}
	public get escapeClose(): DialogComponentCustomElement['escapeClose'] {
		return this.nativeElement.escapeClose;
	}

	/** Controls whether the dialog is open or not. Default is false. */
	@Input({ transform: booleanAttribute })
	public set open(value: DialogComponentCustomElement['open']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.open = value;
		});
	}
	public get open(): DialogComponentCustomElement['open'] {
		return this.nativeElement.open;
	}

	/** Controls whether the dialog is full screen or not. Default is false. */
	@Input({ transform: booleanAttribute })
	public set fullscreen(value: DialogComponentCustomElement['fullscreen']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.fullscreen = value;
		});
	}
	public get fullscreen(): DialogComponentCustomElement['fullscreen'] {
		return this.nativeElement.fullscreen;
	}

	/** The function to call when the dialog wants to open. */
	@Input()
	public set openCallback(value: DialogComponentCustomElement['openCallback']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.openCallback = value;
		});
	}
	public get openCallback(): DialogComponentCustomElement['openCallback'] {
		return this.nativeElement.openCallback;
	}

	/** the function to call when the dialog wants to close. */
	@Input()
	public set closeCallback(value: DialogComponentCustomElement['closeCallback']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.closeCallback = value;
		});
	}
	public get closeCallback(): DialogComponentCustomElement['closeCallback'] {
		return this.nativeElement.closeCallback;
	}

	/** the function to call when the dialog wants to close. */
	@Input()
	public set beforeCloseCallback(value: DialogComponentCustomElement['beforeCloseCallback']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.beforeCloseCallback = value;
		});
	}
	public get beforeCloseCallback(): DialogComponentCustomElement['beforeCloseCallback'] {
		return this.nativeElement.beforeCloseCallback;
	}

	/** Gets/sets the position type when using custom positioning values. Default is 'absolute'. */
	@Input()
	public set positionType(value: DialogComponentCustomElement['positionType']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.positionType = value;
		});
	}
	public get positionType(): DialogComponentCustomElement['positionType'] {
		return this.nativeElement.positionType;
	}

	/** Controls the horizontal position of the dialog surface. */
	@Input()
	public set positionX(value: DialogComponentCustomElement['positionX']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.positionX = value;
		});
	}
	public get positionX(): DialogComponentCustomElement['positionX'] {
		return this.nativeElement.positionX;
	}

	/** Controls the vertical position of the dialog surface. */
	@Input()
	public set positionY(value: DialogComponentCustomElement['positionY']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.positionY = value;
		});
	}
	public get positionY(): DialogComponentCustomElement['positionY'] {
		return this.nativeElement.positionY;
	}

	/** Gets/sets whether the dialog surface can be moved or not. */
	@Input({ transform: booleanAttribute })
	public set moveable(value: DialogComponentCustomElement['moveable']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.moveable = value;
		});
	}
	public get moveable(): DialogComponentCustomElement['moveable'] {
		return this.nativeElement.moveable;
	}

	/** Gets/sets the selector used to target the element that is used as the drag target. */
	@Input()
	public set moveTarget(value: DialogComponentCustomElement['moveTarget']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.moveTarget = value;
		});
	}
	public get moveTarget(): DialogComponentCustomElement['moveTarget'] {
		return this.nativeElement.moveTarget;
	}


	public initializeMoveTarget(...args: Parameters<DialogComponentCustomElement['initializeMoveTarget']>): ReturnType<DialogComponentCustomElement['initializeMoveTarget']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.initializeMoveTarget(...args));
	}


	public resetPosition(...args: Parameters<DialogComponentCustomElement['resetPosition']>): ReturnType<DialogComponentCustomElement['resetPosition']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.resetPosition(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<DialogComponentCustomElement>,
		protected zone: NgZone
	) {
		defineDialogComponent();
		changeDetectorRef.detach();
	}
}
