// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input } from '@angular/core';
import { AppBarNotificationButtonComponent as AppBarNotificationButtonComponentCustomElement, defineAppBarNotificationButtonComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-app-bar-notification-button>` custom element. */
@Component({
  selector: 'forge-app-bar-notification-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class AppBarNotificationButtonComponent {

	/** The forge-app-bar-notification-button element. */
	public readonly nativeElement = this.elementRef.nativeElement;


	@Input({ transform: numberAttribute })
	public set count(value: AppBarNotificationButtonComponentCustomElement['count']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.count = value;
		});
	}
	public get count(): AppBarNotificationButtonComponentCustomElement['count'] {
		return this.nativeElement.count;
	}


	@Input({ transform: booleanAttribute })
	public set dot(value: AppBarNotificationButtonComponentCustomElement['dot']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.dot = value;
		});
	}
	public get dot(): AppBarNotificationButtonComponentCustomElement['dot'] {
		return this.nativeElement.dot;
	}


	@Input()
	public set theme(value: AppBarNotificationButtonComponentCustomElement['theme']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.theme = value;
		});
	}
	public get theme(): AppBarNotificationButtonComponentCustomElement['theme'] {
		return this.nativeElement.theme;
	}


	@Input()
	public set icon(value: AppBarNotificationButtonComponentCustomElement['icon']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.icon = value;
		});
	}
	public get icon(): AppBarNotificationButtonComponentCustomElement['icon'] {
		return this.nativeElement.icon;
	}


	@Input({ transform: booleanAttribute })
	public set showBadge(value: AppBarNotificationButtonComponentCustomElement['showBadge']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.showBadge = value;
		});
	}
	public get showBadge(): AppBarNotificationButtonComponentCustomElement['showBadge'] {
		return this.nativeElement.showBadge;
	}


	public initializedCallback(...args: Parameters<AppBarNotificationButtonComponentCustomElement['initializedCallback']>): ReturnType<AppBarNotificationButtonComponentCustomElement['initializedCallback']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.initializedCallback(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<AppBarNotificationButtonComponentCustomElement>,
		protected zone: NgZone
	) {
		defineAppBarNotificationButtonComponent();
		changeDetectorRef.detach();
	}
}
