// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ChipFieldComponent as ChipFieldComponentCustomElement, defineChipFieldComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-chip-field>` custom element. */
@Component({
  selector: 'forge-chip-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ChipFieldComponent {

	/** The forge-chip-field element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Controls whether or not the value should be set onBlur */
	@Input({ transform: booleanAttribute })
	public set addOnBlur(value: ChipFieldComponentCustomElement['addOnBlur']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.addOnBlur = value;
		});
	}
	public get addOnBlur(): ChipFieldComponentCustomElement['addOnBlur'] {
		return this.nativeElement.addOnBlur;
	}

	/** Controls the density type. */
	@Input()
	public set density(value: ChipFieldComponentCustomElement['density']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.density = value;
		});
	}
	public get density(): ChipFieldComponentCustomElement['density'] {
		return this.nativeElement.density;
	}

	/** Whether the label should always float, never float or float as the user types. */
	@Input()
	public set floatLabelType(value: ChipFieldComponentCustomElement['floatLabelType']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.floatLabelType = value;
		});
	}
	public get floatLabelType(): ChipFieldComponentCustomElement['floatLabelType'] {
		return this.nativeElement.floatLabelType;
	}

	/** The shape type to use. */
	@Input()
	public set shape(value: ChipFieldComponentCustomElement['shape']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.shape = value;
		});
	}
	public get shape(): ChipFieldComponentCustomElement['shape'] {
		return this.nativeElement.shape;
	}

	/** Gets/sets the invalid state. */
	@Input({ transform: booleanAttribute })
	public set invalid(value: ChipFieldComponentCustomElement['invalid']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.invalid = value;
		});
	}
	public get invalid(): ChipFieldComponentCustomElement['invalid'] {
		return this.nativeElement.invalid;
	}

	/** Gets/sets the required state which controls the visibility of the asterisk in the label. */
	@Input({ transform: booleanAttribute })
	public set required(value: ChipFieldComponentCustomElement['required']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.required = value;
		});
	}
	public get required(): ChipFieldComponentCustomElement['required'] {
		return this.nativeElement.required;
	}

	/** Controls whether the label should be floating or not. */
	public floatLabel(...args: Parameters<ChipFieldComponentCustomElement['floatLabel']>): ReturnType<ChipFieldComponentCustomElement['floatLabel']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.floatLabel(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ChipFieldComponentCustomElement>,
		protected zone: NgZone
	) {
		defineChipFieldComponent();
		changeDetectorRef.detach();
	}
}
