// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { PageStateComponent as PageStateComponentCustomElement, definePageStateComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-page-state>` custom element. */
@Component({
  selector: 'forge-page-state',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class PageStateComponent {

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<PageStateComponentCustomElement>,
		protected zone: NgZone
	) {
		definePageStateComponent();
		changeDetectorRef.detach();
	}
}
