// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core'; 
import { defineKeyComponent } from '@tylertech/forge';

import { KeyComponent } from './key.component';

@NgModule({
	imports: [CommonModule],
	declarations: [KeyComponent],
	exports: [KeyComponent]
})
export class ForgeKeyModule {
	constructor() {
		defineKeyComponent();
	}
}