// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { BadgeComponent as BadgeComponentCustomElement } from '@tylertech/forge';

/** The web component class behind the `<forge-badge>` custom element. */
@Component({
  selector: 'forge-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class BadgeComponent {

	/** Controls whether the component renders a simple dot/circle, or allows for content. */
	@Input()
	public set dot(value: BadgeComponentCustomElement['dot'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.dot = value != null && `${value}` !== 'false';
		});
	}

	public get dot(): BadgeComponentCustomElement['dot'] {
		return this.elementRef.nativeElement.dot;
	}

	/** Controls the visibility state. */
	@Input()
	public set open(value: BadgeComponentCustomElement['open'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.open = value != null && `${value}` !== 'false';
		});
	}

	public get open(): BadgeComponentCustomElement['open'] {
		return this.elementRef.nativeElement.open;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<BadgeComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-badge')) {
			window.customElements.define('forge-badge', BadgeComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
