// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { CheckboxComponent as CheckboxComponentCustomElement, defineCheckboxComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-checkbox>` element. */
@Component({
  selector: 'forge-checkbox',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class CheckboxComponent {

	/** The forge-checkbox element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Gets or sets whether or not the checkbox is dense */
	@Input({ transform: booleanAttribute })
	public set dense(value: CheckboxComponentCustomElement['dense']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.dense = value;
		});
	}
	public get dense(): CheckboxComponentCustomElement['dense'] {
		return this.nativeElement.dense;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<CheckboxComponentCustomElement>,
		protected zone: NgZone
	) {
		defineCheckboxComponent();
		changeDetectorRef.detach();
	}
}
