// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input } from '@angular/core';
import { AvatarComponent as AvatarComponentCustomElement, defineAvatarComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-avatar>` element. */
@Component({
  selector: 'forge-avatar',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class AvatarComponent {

	/** The forge-avatar element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Gets/sets the text to display. */
	@Input()
	public set text(value: AvatarComponentCustomElement['text']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.text = value;
		});
	}
	public get text(): AvatarComponentCustomElement['text'] {
		return this.nativeElement.text;
	}

	/** Controls the number of letters to display from the text. By default the text is split on spaces and the first character of each word is used. */
	@Input({ transform: numberAttribute })
	public set letterCount(value: AvatarComponentCustomElement['letterCount']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.letterCount = value;
		});
	}
	public get letterCount(): AvatarComponentCustomElement['letterCount'] {
		return this.nativeElement.letterCount;
	}

	/** Sets the background image URL to use. */
	@Input()
	public set imageUrl(value: AvatarComponentCustomElement['imageUrl']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.imageUrl = value;
		});
	}
	public get imageUrl(): AvatarComponentCustomElement['imageUrl'] {
		return this.nativeElement.imageUrl;
	}

	/** Controls whether the background color is set automatically based on the text value. Does not have any effect when an image URL is specified. */
	@Input({ transform: booleanAttribute })
	public set autoColor(value: AvatarComponentCustomElement['autoColor']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.autoColor = value;
		});
	}
	public get autoColor(): AvatarComponentCustomElement['autoColor'] {
		return this.nativeElement.autoColor;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<AvatarComponentCustomElement>,
		protected zone: NgZone
	) {
		defineAvatarComponent();
		changeDetectorRef.detach();
	}
}
