// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input } from '@angular/core';
import { AppBarProfileButtonComponent as AppBarProfileButtonComponentCustomElement, defineAppBarProfileButtonComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-app-bar-profile-button>` custom element. */
@Component({
  selector: 'forge-app-bar-profile-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class AppBarProfileButtonComponent {

	/** The forge-app-bar-profile-button element. */
	public readonly nativeElement = this.elementRef.nativeElement;


	@Input()
	public set fullName(value: AppBarProfileButtonComponentCustomElement['fullName']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.fullName = value;
		});
	}
	public get fullName(): AppBarProfileButtonComponentCustomElement['fullName'] {
		return this.nativeElement.fullName;
	}


	@Input()
	public set email(value: AppBarProfileButtonComponentCustomElement['email']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.email = value;
		});
	}
	public get email(): AppBarProfileButtonComponentCustomElement['email'] {
		return this.nativeElement.email;
	}


	@Input()
	public set avatarImageUrl(value: AppBarProfileButtonComponentCustomElement['avatarImageUrl']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.avatarImageUrl = value;
		});
	}
	public get avatarImageUrl(): AppBarProfileButtonComponentCustomElement['avatarImageUrl'] {
		return this.nativeElement.avatarImageUrl;
	}


	@Input({ transform: numberAttribute })
	public set avatarLetterCount(value: AppBarProfileButtonComponentCustomElement['avatarLetterCount']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.avatarLetterCount = value;
		});
	}
	public get avatarLetterCount(): AppBarProfileButtonComponentCustomElement['avatarLetterCount'] {
		return this.nativeElement.avatarLetterCount;
	}


	@Input()
	public set avatarText(value: AppBarProfileButtonComponentCustomElement['avatarText']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.avatarText = value;
		});
	}
	public get avatarText(): AppBarProfileButtonComponentCustomElement['avatarText'] {
		return this.nativeElement.avatarText;
	}


	@Input()
	public set avatarIcon(value: AppBarProfileButtonComponentCustomElement['avatarIcon']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.avatarIcon = value;
		});
	}
	public get avatarIcon(): AppBarProfileButtonComponentCustomElement['avatarIcon'] {
		return this.nativeElement.avatarIcon;
	}


	@Input({ transform: booleanAttribute })
	public set signOutButton(value: AppBarProfileButtonComponentCustomElement['signOutButton']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.signOutButton = value;
		});
	}
	public get signOutButton(): AppBarProfileButtonComponentCustomElement['signOutButton'] {
		return this.nativeElement.signOutButton;
	}


	@Input({ transform: booleanAttribute })
	public set profileButton(value: AppBarProfileButtonComponentCustomElement['profileButton']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.profileButton = value;
		});
	}
	public get profileButton(): AppBarProfileButtonComponentCustomElement['profileButton'] {
		return this.nativeElement.profileButton;
	}


	@Input()
	public set signOutButtonText(value: AppBarProfileButtonComponentCustomElement['signOutButtonText']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.signOutButtonText = value;
		});
	}
	public get signOutButtonText(): AppBarProfileButtonComponentCustomElement['signOutButtonText'] {
		return this.nativeElement.signOutButtonText;
	}


	@Input()
	public set profileButtonText(value: AppBarProfileButtonComponentCustomElement['profileButtonText']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.profileButtonText = value;
		});
	}
	public get profileButtonText(): AppBarProfileButtonComponentCustomElement['profileButtonText'] {
		return this.nativeElement.profileButtonText;
	}


	@Input({ transform: booleanAttribute })
	public set open(value: AppBarProfileButtonComponentCustomElement['open']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.open = value;
		});
	}
	public get open(): AppBarProfileButtonComponentCustomElement['open'] {
		return this.nativeElement.open;
	}

	/** Sets the profile card builder callback that will be used to add extra content to the profile card. */
	@Input()
	public set profileCardBuilder(value: AppBarProfileButtonComponentCustomElement['profileCardBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.profileCardBuilder = value;
		});
	}
	public get profileCardBuilder(): AppBarProfileButtonComponentCustomElement['profileCardBuilder'] {
		return this.nativeElement.profileCardBuilder;
	}


	public initializedCallback(...args: Parameters<AppBarProfileButtonComponentCustomElement['initializedCallback']>): ReturnType<AppBarProfileButtonComponentCustomElement['initializedCallback']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.initializedCallback(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<AppBarProfileButtonComponentCustomElement>,
		protected zone: NgZone
	) {
		defineAppBarProfileButtonComponent();
		changeDetectorRef.detach();
	}
}
