// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { FloatingActionButton as FloatingActionButtonCustomElement } from '@tylertech/forge';

/** The custom element class behind the `<forge-fab>` element. */
@Component({
  selector: 'forge-fab',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class FloatingActionButton {

	/** Gets/sets the exited state. */
	@Input()
	public set exited(value: FloatingActionButtonCustomElement['exited'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.exited = value != null && `${value}` !== 'false';
		});
	}

	public get exited(): FloatingActionButtonCustomElement['exited'] {
		return this.elementRef.nativeElement.exited;
	}

	/** Gets/sets the mini state. */
	@Input()
	public set mini(value: FloatingActionButtonCustomElement['mini'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.mini = value != null && `${value}` !== 'false';
		});
	}

	public get mini(): FloatingActionButtonCustomElement['mini'] {
		return this.elementRef.nativeElement.mini;
	}

	/** Gets/sets the extended state. */
	@Input()
	public set extended(value: FloatingActionButtonCustomElement['extended'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.extended = value != null && `${value}` !== 'false';
		});
	}

	public get extended(): FloatingActionButtonCustomElement['extended'] {
		return this.elementRef.nativeElement.extended;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<FloatingActionButtonCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-fab')) {
			window.customElements.define('forge-fab', FloatingActionButtonCustomElement);
		}
		changeDetectorRef.detach();
	}
}
