// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { TextFieldComponent as TextFieldComponentCustomElement, defineTextFieldComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-text-field>` custom element. */
@Component({
  selector: 'forge-text-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class TextFieldComponent {

	/** Controls the density type. */
	@Input()
	public set density(value: TextFieldComponentCustomElement['density']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.density = value;
		});
	}

	public get density(): TextFieldComponentCustomElement['density'] {
		return this.elementRef.nativeElement.density;
	}

	/** Whether the label should always float, never float or float as the user types. */
	@Input()
	public set floatLabelType(value: TextFieldComponentCustomElement['floatLabelType']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.floatLabelType = value;
		});
	}

	public get floatLabelType(): TextFieldComponentCustomElement['floatLabelType'] {
		return this.elementRef.nativeElement.floatLabelType;
	}

	/** The shape type to use. */
	@Input()
	public set shape(value: TextFieldComponentCustomElement['shape']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.shape = value;
		});
	}

	public get shape(): TextFieldComponentCustomElement['shape'] {
		return this.elementRef.nativeElement.shape;
	}

	/** Gets/sets the invalid state. */
	@Input()
	public set invalid(value: TextFieldComponentCustomElement['invalid'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.invalid = value != null && `${value}` !== 'false';
		});
	}

	public get invalid(): TextFieldComponentCustomElement['invalid'] {
		return this.elementRef.nativeElement.invalid;
	}

	/** Gets/sets the required state which controls the visibility of the asterisk in the label. */
	@Input()
	public set required(value: TextFieldComponentCustomElement['required'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.required = value != null && `${value}` !== 'false';
		});
	}

	public get required(): TextFieldComponentCustomElement['required'] {
		return this.elementRef.nativeElement.required;
	}

	/** Controls whether the label should be floating or not. */
	public floatLabel(...args: Parameters<TextFieldComponentCustomElement['floatLabel']>): ReturnType<TextFieldComponentCustomElement['floatLabel']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.floatLabel(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<TextFieldComponentCustomElement>,
		protected zone: NgZone
	) {
		defineTextFieldComponent();
		changeDetectorRef.detach();
	}
}
