// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { CardComponent as CardComponentCustomElement, defineCardComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-card>` component. */
@Component({
  selector: 'forge-card',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class CardComponent {

	/** Gets/sets whether the card is using the outlined style or not. */
	@Input()
	public set outlined(value: CardComponentCustomElement['outlined'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.outlined = value != null && `${value}` !== 'false';
		});
	}

	public get outlined(): CardComponentCustomElement['outlined'] {
		return this.elementRef.nativeElement.outlined;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<CardComponentCustomElement>,
		protected zone: NgZone
	) {
		defineCardComponent();
		changeDetectorRef.detach();
	}
}
