// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { BottomSheetComponent as BottomSheetComponentCustomElement } from '@tylertech/forge';

/** The web component class behind the `<forge-bottom-sheet>` custom element. */
@Component({
  selector: 'forge-bottom-sheet',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class BottomSheetComponent {

	/** Controls whether clicking the backdrop closes the bottom-sheet or not. Default is true. */
	@Input()
	public set backdropClose(value: BottomSheetComponentCustomElement['backdropClose'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.backdropClose = value != null && `${value}` !== 'false';
		});
	}

	public get backdropClose(): BottomSheetComponentCustomElement['backdropClose'] {
		return this.elementRef.nativeElement.backdropClose;
	}

	/** Controls whether pressing the escape key closes the bottom-sheet or not. Default is true. */
	@Input()
	public set escapeClose(value: BottomSheetComponentCustomElement['escapeClose'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.escapeClose = value != null && `${value}` !== 'false';
		});
	}

	public get escapeClose(): BottomSheetComponentCustomElement['escapeClose'] {
		return this.elementRef.nativeElement.escapeClose;
	}

	/** Controls whether the bottom-sheet is open or not. Default is false. */
	@Input()
	public set open(value: BottomSheetComponentCustomElement['open'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.open = value != null && `${value}` !== 'false';
		});
	}

	public get open(): BottomSheetComponentCustomElement['open'] {
		return this.elementRef.nativeElement.open;
	}

	/** Controls whether the bottom-sheet is full screen or not. Default is false. */
	@Input()
	public set fullscreen(value: BottomSheetComponentCustomElement['fullscreen'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.fullscreen = value != null && `${value}` !== 'false';
		});
	}

	public get fullscreen(): BottomSheetComponentCustomElement['fullscreen'] {
		return this.elementRef.nativeElement.fullscreen;
	}

	/** Shows a backdrop to prevent interacting with other content until the bottom sheet is dismissed.  Default is false. */
	@Input()
	public set showBackdrop(value: BottomSheetComponentCustomElement['showBackdrop'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.showBackdrop = value != null && `${value}` !== 'false';
		});
	}

	public get showBackdrop(): BottomSheetComponentCustomElement['showBackdrop'] {
		return this.elementRef.nativeElement.showBackdrop;
	}

	/** The function to call when the bottom-sheet wants to open. */
	@Input()
	public set openCallback(value: BottomSheetComponentCustomElement['openCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.openCallback = value;
		});
	}

	public get openCallback(): BottomSheetComponentCustomElement['openCallback'] {
		return this.elementRef.nativeElement.openCallback;
	}

	/** the function to call when the bottom-sheet wants to close. */
	@Input()
	public set closeCallback(value: BottomSheetComponentCustomElement['closeCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.closeCallback = value;
		});
	}

	public get closeCallback(): BottomSheetComponentCustomElement['closeCallback'] {
		return this.elementRef.nativeElement.closeCallback;
	}

	/** the function to call when the bottom-sheet wants to close. */
	@Input()
	public set beforeCloseCallback(value: BottomSheetComponentCustomElement['beforeCloseCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.beforeCloseCallback = value;
		});
	}

	public get beforeCloseCallback(): BottomSheetComponentCustomElement['beforeCloseCallback'] {
		return this.elementRef.nativeElement.beforeCloseCallback;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<BottomSheetComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-bottom-sheet')) {
			window.customElements.define('forge-bottom-sheet', BottomSheetComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
