// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { AppBarHelpButtonComponent as AppBarHelpButtonComponentCustomElement, defineAppBarHelpButtonComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-app-bar-help-button',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class AppBarHelpButtonComponent {

	/** The forge-app-bar-help-button element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** The menu options to display when the button is clicked */
	@Input()
	public set options(value: AppBarHelpButtonComponentCustomElement['options']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.options = value;
		});
	}
	public get options(): AppBarHelpButtonComponentCustomElement['options'] {
		return this.nativeElement.options;
	}

	/** The name of an alternative icon to display. */
	@Input()
	public set icon(value: AppBarHelpButtonComponentCustomElement['icon']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.icon = value;
		});
	}
	public get icon(): AppBarHelpButtonComponentCustomElement['icon'] {
		return this.nativeElement.icon;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<AppBarHelpButtonComponentCustomElement>,
		protected zone: NgZone
	) {
		defineAppBarHelpButtonComponent();
		changeDetectorRef.detach();
	}
}
