// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { DatePickerComponent as DatePickerComponentCustomElement } from '@tylertech/forge';

/** The custom element class behind the `<forge-date-picker>` element. */
@Component({
  selector: 'forge-date-picker',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class DatePickerComponent {

	/** Gets/sets the value of the component. */
	@Input()
	public set value(value: DatePickerComponentCustomElement['value']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.value = value;
		});
	}

	public get value(): DatePickerComponentCustomElement['value'] {
		return this.elementRef.nativeElement.value;
	}

	/** Gets/sets the minimum date the calendar will allow. */
	@Input()
	public set min(value: DatePickerComponentCustomElement['min']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.min = value;
		});
	}

	public get min(): DatePickerComponentCustomElement['min'] {
		return this.elementRef.nativeElement.min;
	}

	/** Gets/sets the maximum date the calendar will allow. */
	@Input()
	public set max(value: DatePickerComponentCustomElement['max']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.max = value;
		});
	}

	public get max(): DatePickerComponentCustomElement['max'] {
		return this.elementRef.nativeElement.max;
	}

	/** Gets/sets the dates that are restricted from being selected. */
	@Input()
	public set disabledDates(value: DatePickerComponentCustomElement['disabledDates']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabledDates = value;
		});
	}

	public get disabledDates(): DatePickerComponentCustomElement['disabledDates'] {
		return this.elementRef.nativeElement.disabledDates;
	}

	/** Gets/sets whether the calendar dropdown is open. */
	@Input()
	public set open(value: DatePickerComponentCustomElement['open'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.open = value != null && `${value}` !== 'false';
		});
	}

	public get open(): DatePickerComponentCustomElement['open'] {
		return this.elementRef.nativeElement.open;
	}

	/** Gets/sets the CSS classes that are applied to the popup element. */
	@Input()
	public set popupClasses(value: DatePickerComponentCustomElement['popupClasses']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.popupClasses = value;
		});
	}

	public get popupClasses(): DatePickerComponentCustomElement['popupClasses'] {
		return this.elementRef.nativeElement.popupClasses;
	}

	/** Gets/sets whether the date picker is disabled or not. */
	@Input()
	public set disabled(value: DatePickerComponentCustomElement['disabled'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabled = value != null && `${value}` !== 'false';
		});
	}

	public get disabled(): DatePickerComponentCustomElement['disabled'] {
		return this.elementRef.nativeElement.disabled;
	}

	/** Gets/sets whether the input mask is applied or not. */
	@Input()
	public set masked(value: DatePickerComponentCustomElement['masked'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.masked = value != null && `${value}` !== 'false';
		});
	}

	public get masked(): DatePickerComponentCustomElement['masked'] {
		return this.elementRef.nativeElement.masked;
	}

	/** Gets/sets the mask format that displayed in the input. Default is `MM/DD/YYYY` */
	@Input()
	public set maskFormat(value: DatePickerComponentCustomElement['maskFormat']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.maskFormat = value;
		});
	}

	public get maskFormat(): DatePickerComponentCustomElement['maskFormat'] {
		return this.elementRef.nativeElement.maskFormat;
	}

	/** Gets/sets whether the mask format is displayed in the input or not. Only applies if `masked` is `true`. */
	@Input()
	public set showMaskFormat(value: DatePickerComponentCustomElement['showMaskFormat'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.showMaskFormat = value != null && `${value}` !== 'false';
		});
	}

	public get showMaskFormat(): DatePickerComponentCustomElement['showMaskFormat'] {
		return this.elementRef.nativeElement.showMaskFormat;
	}

	/** Gets/sets the type for the `value` property and `forge-date-picker-change` event. */
	@Input()
	public set valueMode(value: DatePickerComponentCustomElement['valueMode']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.valueMode = value;
		});
	}

	public get valueMode(): DatePickerComponentCustomElement['valueMode'] {
		return this.elementRef.nativeElement.valueMode;
	}

	/** Gets/sets whether the native input will be notified of value changes via the `input` and `change` events. */
	@Input()
	public set notifyInputValueChanges(value: DatePickerComponentCustomElement['notifyInputValueChanges'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.notifyInputValueChanges = value != null && `${value}` !== 'false';
		});
	}

	public get notifyInputValueChanges(): DatePickerComponentCustomElement['notifyInputValueChanges'] {
		return this.elementRef.nativeElement.notifyInputValueChanges;
	}

	/** Gets/sets whether to allow an invalid date to be input. When true, the date picker will not clear out the value of the input if the date was invalid (i.e. could not be parsed). */
	@Input()
	public set allowInvalidDate(value: DatePickerComponentCustomElement['allowInvalidDate'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.allowInvalidDate = value != null && `${value}` !== 'false';
		});
	}

	public get allowInvalidDate(): DatePickerComponentCustomElement['allowInvalidDate'] {
		return this.elementRef.nativeElement.allowInvalidDate;
	}

	/** Gets/sets whether the today button is visible in the popup. */
	@Input()
	public set showToday(value: DatePickerComponentCustomElement['showToday'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.showToday = value != null && `${value}` !== 'false';
		});
	}

	public get showToday(): DatePickerComponentCustomElement['showToday'] {
		return this.elementRef.nativeElement.showToday;
	}

	/** Gets/sets whether the clear button is visible in the popup. */
	@Input()
	public set showClear(value: DatePickerComponentCustomElement['showClear'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.showClear = value != null && `${value}` !== 'false';
		});
	}

	public get showClear(): DatePickerComponentCustomElement['showClear'] {
		return this.elementRef.nativeElement.showClear;
	}

	/** Sets the callback to use for parsing a date value string to a `Date` object. */
	@Input()
	public set parseCallback(value: DatePickerComponentCustomElement['parseCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.parseCallback = value;
		});
	}

	public get parseCallback(): DatePickerComponentCustomElement['parseCallback'] {
		return this.elementRef.nativeElement.parseCallback;
	}

	/** Sets the callback to use for formatting `Date` value to a custom string format. */
	@Input()
	public set formatCallback(value: DatePickerComponentCustomElement['formatCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.formatCallback = value;
		});
	}

	public get formatCallback(): DatePickerComponentCustomElement['formatCallback'] {
		return this.elementRef.nativeElement.formatCallback;
	}

	/** Sets the callback to use when altering default mask entry. */
	@Input()
	public set prepareMaskCallback(value: DatePickerComponentCustomElement['prepareMaskCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.prepareMaskCallback = value;
		});
	}

	public get prepareMaskCallback(): DatePickerComponentCustomElement['prepareMaskCallback'] {
		return this.elementRef.nativeElement.prepareMaskCallback;
	}

	/** Sets the days of the week to disable from selection. */
	@Input()
	public set disabledDaysOfWeek(value: DatePickerComponentCustomElement['disabledDaysOfWeek']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabledDaysOfWeek = value;
		});
	}

	public get disabledDaysOfWeek(): DatePickerComponentCustomElement['disabledDaysOfWeek'] {
		return this.elementRef.nativeElement.disabledDaysOfWeek;
	}

	/** Sets the callback to use for testing whether a specific date should be disabled or not. */
	@Input()
	public set disableDayCallback(value: DatePickerComponentCustomElement['disableDayCallback']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disableDayCallback = value;
		});
	}

	public get disableDayCallback(): DatePickerComponentCustomElement['disableDayCallback'] {
		return this.elementRef.nativeElement.disableDayCallback;
	}

	/** Sets the year range. */
	@Input()
	public set yearRange(value: DatePickerComponentCustomElement['yearRange']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.yearRange = value;
		});
	}

	public get yearRange(): DatePickerComponentCustomElement['yearRange'] {
		return this.elementRef.nativeElement.yearRange;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<DatePickerComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-date-picker')) {
			window.customElements.define('forge-date-picker', DatePickerComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
