// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { AppBarSearchComponent as AppBarSearchComponentCustomElement } from '@tylertech/forge';

/** The web component class behind the `<forge-app-bar-search>` custom element. */
@Component({
  selector: 'forge-app-bar-search',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class AppBarSearchComponent {

	/** Gets/sets the value. */
	@Input()
	public set value(value: AppBarSearchComponentCustomElement['value']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.value = value;
		});
	}

	public get value(): AppBarSearchComponentCustomElement['value'] {
		return this.elementRef.nativeElement.value;
	}

	/** Gets/sets the disabled state of the search input. */
	@Input()
	public set disabled(value: AppBarSearchComponentCustomElement['disabled'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabled = value != null && `${value}` !== 'false';
		});
	}

	public get disabled(): AppBarSearchComponentCustomElement['disabled'] {
		return this.elementRef.nativeElement.disabled;
	}

	/** Gets/sets whether this is a combined search box with search options. */
	@Input()
	public set combined(value: AppBarSearchComponentCustomElement['combined'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.combined = value != null && `${value}` !== 'false';
		});
	}

	public get combined(): AppBarSearchComponentCustomElement['combined'] {
		return this.elementRef.nativeElement.combined;
	}

	/** Gets/sets seelcted option for the combined search dropdown. */
	@Input()
	public set combinedOptions(value: AppBarSearchComponentCustomElement['combinedOptions']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.combinedOptions = value;
		});
	}

	public get combinedOptions(): AppBarSearchComponentCustomElement['combinedOptions'] {
		return this.elementRef.nativeElement.combinedOptions;
	}

	/** Gets/sets selected option for the combined search dropdown. */
	@Input()
	public set selectedCombinedOption(value: AppBarSearchComponentCustomElement['selectedCombinedOption']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.selectedCombinedOption = value;
		});
	}

	public get selectedCombinedOption(): AppBarSearchComponentCustomElement['selectedCombinedOption'] {
		return this.elementRef.nativeElement.selectedCombinedOption;
	}

	/** Gets/sets whether the global icon is displayed at the end of the input. */
	@Input()
	public set global(value: AppBarSearchComponentCustomElement['global'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.global = value != null && `${value}` !== 'false';
		});
	}

	public get global(): AppBarSearchComponentCustomElement['global'] {
		return this.elementRef.nativeElement.global;
	}

	/** Sets the input placeholder value. */
	@Input()
	public set placeholder(value: AppBarSearchComponentCustomElement['placeholder']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.placeholder = value;
		});
	}

	public get placeholder(): AppBarSearchComponentCustomElement['placeholder'] {
		return this.elementRef.nativeElement.placeholder;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<AppBarSearchComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-app-bar-search')) {
			window.customElements.define('forge-app-bar-search', AppBarSearchComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
