// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { defineTimelineComponent } from '@tylertech/forge';

import { TimelineComponent } from './timeline.component';
import { ForgeTimelineBreakModule } from '../timeline-break';
import { ForgeTimelineItemModule } from '../timeline-item';

@NgModule({
  imports: [CommonModule],
  declarations: [TimelineComponent],
  exports: [
    TimelineComponent,
    ForgeTimelineBreakModule,
    ForgeTimelineItemModule,
  ],
})
export class ForgeTimelineModule {
  constructor() {
    defineTimelineComponent();
  }
}
