// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { CircularProgressComponent as CircularProgressComponentCustomElement } from '@tylertech/forge';

/** The web component class behind the `<forge-circular-progress>` custom element. */
@Component({
  selector: 'forge-circular-progress',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class CircularProgressComponent {


	@Input()
	public set open(value: CircularProgressComponentCustomElement['open'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.open = value != null && `${value}` !== 'false';
		});
	}

	public get open(): CircularProgressComponentCustomElement['open'] {
		return this.elementRef.nativeElement.open;
	}


	@Input()
	public set determinate(value: CircularProgressComponentCustomElement['determinate'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.determinate = value != null && `${value}` !== 'false';
		});
	}

	public get determinate(): CircularProgressComponentCustomElement['determinate'] {
		return this.elementRef.nativeElement.determinate;
	}


	@Input()
	public set progress(value: CircularProgressComponentCustomElement['progress'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.progress = +value;
		});
	}

	public get progress(): CircularProgressComponentCustomElement['progress'] {
		return this.elementRef.nativeElement.progress;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<CircularProgressComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-circular-progress')) {
			window.customElements.define('forge-circular-progress', CircularProgressComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
