// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input } from '@angular/core';
import { LinearProgressComponent as LinearProgressComponentCustomElement, defineLinearProgressComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-linear-progress>` custom element. */
@Component({
  selector: 'forge-linear-progress',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class LinearProgressComponent {

	/** The forge-linear-progress element. */
	public readonly nativeElement = this.elementRef.nativeElement;


	@Input({ transform: booleanAttribute })
	public set determinate(value: LinearProgressComponentCustomElement['determinate']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.determinate = value;
		});
	}
	public get determinate(): LinearProgressComponentCustomElement['determinate'] {
		return this.nativeElement.determinate;
	}


	@Input({ transform: numberAttribute })
	public set progress(value: LinearProgressComponentCustomElement['progress']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.progress = value;
		});
	}
	public get progress(): LinearProgressComponentCustomElement['progress'] {
		return this.nativeElement.progress;
	}


	@Input({ transform: numberAttribute })
	public set buffer(value: LinearProgressComponentCustomElement['buffer']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.buffer = value;
		});
	}
	public get buffer(): LinearProgressComponentCustomElement['buffer'] {
		return this.nativeElement.buffer;
	}


	@Input({ transform: booleanAttribute })
	public set visible(value: LinearProgressComponentCustomElement['visible']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.visible = value;
		});
	}
	public get visible(): LinearProgressComponentCustomElement['visible'] {
		return this.nativeElement.visible;
	}


	public open(...args: Parameters<LinearProgressComponentCustomElement['open']>): ReturnType<LinearProgressComponentCustomElement['open']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.open(...args));
	}


	public close(...args: Parameters<LinearProgressComponentCustomElement['close']>): ReturnType<LinearProgressComponentCustomElement['close']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.close(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<LinearProgressComponentCustomElement>,
		protected zone: NgZone
	) {
		defineLinearProgressComponent();
		changeDetectorRef.detach();
	}
}
