// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { LinearProgressComponent as LinearProgressComponentCustomElement } from '@tylertech/forge';

/** The web component class behind the `<forge-linear-progress>` custom element. */
@Component({
  selector: 'forge-linear-progress',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class LinearProgressComponent {


	@Input()
	public set determinate(value: LinearProgressComponentCustomElement['determinate'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.determinate = value != null && `${value}` !== 'false';
		});
	}

	public get determinate(): LinearProgressComponentCustomElement['determinate'] {
		return this.elementRef.nativeElement.determinate;
	}


	@Input()
	public set progress(value: LinearProgressComponentCustomElement['progress'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.progress = +value;
		});
	}

	public get progress(): LinearProgressComponentCustomElement['progress'] {
		return this.elementRef.nativeElement.progress;
	}


	@Input()
	public set buffer(value: LinearProgressComponentCustomElement['buffer'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.buffer = +value;
		});
	}

	public get buffer(): LinearProgressComponentCustomElement['buffer'] {
		return this.elementRef.nativeElement.buffer;
	}


	@Input()
	public set visible(value: LinearProgressComponentCustomElement['visible'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.visible = value != null && `${value}` !== 'false';
		});
	}

	public get visible(): LinearProgressComponentCustomElement['visible'] {
		return this.elementRef.nativeElement.visible;
	}


	public open(...args: Parameters<LinearProgressComponentCustomElement['open']>): ReturnType<LinearProgressComponentCustomElement['open']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.open(...args));
	}


	public close(...args: Parameters<LinearProgressComponentCustomElement['close']>): ReturnType<LinearProgressComponentCustomElement['close']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.close(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<LinearProgressComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-linear-progress')) {
			window.customElements.define('forge-linear-progress', LinearProgressComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
