// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { StepperComponent as StepperComponentCustomElement, defineStepperComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-stepper>` custom element. */
@Component({
  selector: 'forge-stepper',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class StepperComponent {

	/** The step configurations. */
	@Input()
	public set steps(value: StepperComponentCustomElement['steps']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.steps = value;
		});
	}

	public get steps(): StepperComponentCustomElement['steps'] {
		return this.elementRef.nativeElement.steps;
	}

	/** The active step index. */
	@Input()
	public set selectedIndex(value: StepperComponentCustomElement['selectedIndex'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.selectedIndex = +value;
		});
	}

	public get selectedIndex(): StepperComponentCustomElement['selectedIndex'] {
		return this.elementRef.nativeElement.selectedIndex;
	}

	/** Whether the stepper is linear or non-linear. */
	@Input()
	public set linear(value: StepperComponentCustomElement['linear'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.linear = value != null && `${value}` !== 'false';
		});
	}

	public get linear(): StepperComponentCustomElement['linear'] {
		return this.elementRef.nativeElement.linear;
	}

	/** Whether the stepper uses the default or alternative label layout mode. */
	@Input()
	public set alternative(value: StepperComponentCustomElement['alternative'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.alternative = value != null && `${value}` !== 'false';
		});
	}

	public get alternative(): StepperComponentCustomElement['alternative'] {
		return this.elementRef.nativeElement.alternative;
	}

	/** The layout mode of the stepper. */
	@Input()
	public set layoutMode(value: StepperComponentCustomElement['layoutMode']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.layoutMode = value;
		});
	}

	public get layoutMode(): StepperComponentCustomElement['layoutMode'] {
		return this.elementRef.nativeElement.layoutMode;
	}

	/** The layout alignment of the stepper. */
	@Input()
	public set layoutAlign(value: StepperComponentCustomElement['layoutAlign']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.layoutAlign = value;
		});
	}

	public get layoutAlign(): StepperComponentCustomElement['layoutAlign'] {
		return this.elementRef.nativeElement.layoutAlign;
	}


	@Input()
	public set disabled(value: StepperComponentCustomElement['disabled'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabled = value != null && `${value}` !== 'false';
		});
	}

	public get disabled(): StepperComponentCustomElement['disabled'] {
		return this.elementRef.nativeElement.disabled;
	}


	@Input()
	public set vertical(value: StepperComponentCustomElement['vertical'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.vertical = value != null && `${value}` !== 'false';
		});
	}

	public get vertical(): StepperComponentCustomElement['vertical'] {
		return this.elementRef.nativeElement.vertical;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<StepperComponentCustomElement>,
		protected zone: NgZone
	) {
		defineStepperComponent();
		changeDetectorRef.detach();
	}
}
