// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { AccordionComponent as AccordionComponentCustomElement, defineAccordionComponent } from '@tylertech/forge';

/**
 * The custom element class behind the `<forge-accordion>` web component.
 * 
 * This component is intended to wrap and orchestrate child expansion panels
 * so that only one expansion panel is open at a time.
 */
@Component({
  selector: 'forge-accordion',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class AccordionComponent {

	/** Gets/sets the selector to use for finding the child expansion panels. Defaults to searching the direct children for `<forge-expansion-panel>` elements. */
	@Input()
	public set panelSelector(value: AccordionComponentCustomElement['panelSelector']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.panelSelector = value;
		});
	}

	public get panelSelector(): AccordionComponentCustomElement['panelSelector'] {
		return this.elementRef.nativeElement.panelSelector;
	}


	public initializedCallback(...args: Parameters<AccordionComponentCustomElement['initializedCallback']>): ReturnType<AccordionComponentCustomElement['initializedCallback']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.initializedCallback(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<AccordionComponentCustomElement>,
		protected zone: NgZone
	) {
		defineAccordionComponent();
		changeDetectorRef.detach();
	}
}
