// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ButtonToggleGroupComponent as ButtonToggleGroupComponentCustomElement, defineButtonToggleGroupComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-button-toggle-group>` custom element. */
@Component({
  selector: 'forge-button-toggle-group',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ButtonToggleGroupComponent {


	@Input()
	public set value(value: ButtonToggleGroupComponentCustomElement['value']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.value = value;
		});
	}

	public get value(): ButtonToggleGroupComponentCustomElement['value'] {
		return this.elementRef.nativeElement.value;
	}


	@Input()
	public set multiple(value: ButtonToggleGroupComponentCustomElement['multiple'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.multiple = value != null && `${value}` !== 'false';
		});
	}

	public get multiple(): ButtonToggleGroupComponentCustomElement['multiple'] {
		return this.elementRef.nativeElement.multiple;
	}


	@Input()
	public set mandatory(value: ButtonToggleGroupComponentCustomElement['mandatory'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.mandatory = value != null && `${value}` !== 'false';
		});
	}

	public get mandatory(): ButtonToggleGroupComponentCustomElement['mandatory'] {
		return this.elementRef.nativeElement.mandatory;
	}


	@Input()
	public set vertical(value: ButtonToggleGroupComponentCustomElement['vertical'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.vertical = value != null && `${value}` !== 'false';
		});
	}

	public get vertical(): ButtonToggleGroupComponentCustomElement['vertical'] {
		return this.elementRef.nativeElement.vertical;
	}


	@Input()
	public set stretch(value: ButtonToggleGroupComponentCustomElement['stretch'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.stretch = value != null && `${value}` !== 'false';
		});
	}

	public get stretch(): ButtonToggleGroupComponentCustomElement['stretch'] {
		return this.elementRef.nativeElement.stretch;
	}


	@Input()
	public set dense(value: ButtonToggleGroupComponentCustomElement['dense'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.dense = value != null && `${value}` !== 'false';
		});
	}

	public get dense(): ButtonToggleGroupComponentCustomElement['dense'] {
		return this.elementRef.nativeElement.dense;
	}


	@Input()
	public set disabled(value: ButtonToggleGroupComponentCustomElement['disabled'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabled = value != null && `${value}` !== 'false';
		});
	}

	public get disabled(): ButtonToggleGroupComponentCustomElement['disabled'] {
		return this.elementRef.nativeElement.disabled;
	}


	@Input()
	public set options(value: ButtonToggleGroupComponentCustomElement['options']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.options = value;
		});
	}

	public get options(): ButtonToggleGroupComponentCustomElement['options'] {
		return this.elementRef.nativeElement.options;
	}


	public initializedCallback(...args: Parameters<ButtonToggleGroupComponentCustomElement['initializedCallback']>): ReturnType<ButtonToggleGroupComponentCustomElement['initializedCallback']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.initializedCallback(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ButtonToggleGroupComponentCustomElement>,
		protected zone: NgZone
	) {
		defineButtonToggleGroupComponent();
		changeDetectorRef.detach();
	}
}
