// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { ButtonToggleGroupComponent } from './button-toggle-group.component';

@NgModule({
	imports: [CommonModule],
	declarations: [ButtonToggleGroupComponent],
	exports: [ButtonToggleGroupComponent]
})
export class ForgeButtonToggleGroupModule {}