// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { LabelValueComponent as LabelValueComponentCustomElement, defineLabelValueComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-label-value>` custom element. */
@Component({
  selector: 'forge-label-value',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class LabelValueComponent {

	/** The forge-label-value element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Gets/sets the empty state. */
	@Input({ transform: booleanAttribute })
	public set empty(value: LabelValueComponentCustomElement['empty']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.empty = value;
		});
	}
	public get empty(): LabelValueComponentCustomElement['empty'] {
		return this.nativeElement.empty;
	}

	/** Gets/sets the wrap-content attribute. */
	@Input({ transform: booleanAttribute })
	public set ellipsis(value: LabelValueComponentCustomElement['ellipsis']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.ellipsis = value;
		});
	}
	public get ellipsis(): LabelValueComponentCustomElement['ellipsis'] {
		return this.nativeElement.ellipsis;
	}

	/** Controls the density type. */
	@Input()
	public set density(value: LabelValueComponentCustomElement['density']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.density = value;
		});
	}
	public get density(): LabelValueComponentCustomElement['density'] {
		return this.nativeElement.density;
	}

	/** Gets/sets the alignment. */
	@Input()
	public set align(value: LabelValueComponentCustomElement['align']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.align = value;
		});
	}
	public get align(): LabelValueComponentCustomElement['align'] {
		return this.nativeElement.align;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<LabelValueComponentCustomElement>,
		protected zone: NgZone
	) {
		defineLabelValueComponent();
		changeDetectorRef.detach();
	}
}
