// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, numberAttribute, Input } from '@angular/core';
import { SelectComponent as SelectComponentCustomElement, defineSelectComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-select>` component. */
@Component({
  selector: 'forge-select',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class SelectComponent {

	/** The forge-select element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Gets/sets the label text. */
	@Input()
	public set label(value: SelectComponentCustomElement['label']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.label = value;
		});
	}
	public get label(): SelectComponentCustomElement['label'] {
		return this.nativeElement.label;
	}

	/** Gets/sets the disabled state. */
	@Input({ transform: booleanAttribute })
	public set disabled(value: SelectComponentCustomElement['disabled']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.disabled = value;
		});
	}
	public get disabled(): SelectComponentCustomElement['disabled'] {
		return this.nativeElement.disabled;
	}

	/** Gets/sets the invalid state. */
	@Input({ transform: booleanAttribute })
	public set invalid(value: SelectComponentCustomElement['invalid']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.invalid = value;
		});
	}
	public get invalid(): SelectComponentCustomElement['invalid'] {
		return this.nativeElement.invalid;
	}

	/** Gets/sets the required state which controls the visibility of the asterisk in the label. */
	@Input({ transform: booleanAttribute })
	public set required(value: SelectComponentCustomElement['required']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.required = value;
		});
	}
	public get required(): SelectComponentCustomElement['required'] {
		return this.nativeElement.required;
	}

	/** Controls the density type. */
	@Input()
	public set density(value: SelectComponentCustomElement['density']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.density = value;
		});
	}
	public get density(): SelectComponentCustomElement['density'] {
		return this.nativeElement.density;
	}

	/** Whether the label should always float, never float or float as the user types. */
	@Input()
	public set floatLabelType(value: SelectComponentCustomElement['floatLabelType']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.floatLabelType = value;
		});
	}
	public get floatLabelType(): SelectComponentCustomElement['floatLabelType'] {
		return this.nativeElement.floatLabelType;
	}

	/** The shape type to use. */
	@Input()
	public set shape(value: SelectComponentCustomElement['shape']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.shape = value;
		});
	}
	public get shape(): SelectComponentCustomElement['shape'] {
		return this.nativeElement.shape;
	}

	/** Gets/sets the placeholder text. */
	@Input()
	public set placeholder(value: SelectComponentCustomElement['placeholder']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.placeholder = value;
		});
	}
	public get placeholder(): SelectComponentCustomElement['placeholder'] {
		return this.nativeElement.placeholder;
	}

	/** Gets/sets the value. */
	@Input()
	public set value(value: SelectComponentCustomElement['value']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.value = value;
		});
	}
	public get value(): SelectComponentCustomElement['value'] {
		return this.nativeElement.value;
	}

	/** Gets/sets the selected index. */
	@Input()
	public set selectedIndex(value: SelectComponentCustomElement['selectedIndex']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.selectedIndex = value;
		});
	}
	public get selectedIndex(): SelectComponentCustomElement['selectedIndex'] {
		return this.nativeElement.selectedIndex;
	}

	/** Gets/sets the available options. */
	@Input()
	public set options(value: SelectComponentCustomElement['options']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.options = value;
		});
	}
	public get options(): SelectComponentCustomElement['options'] {
		return this.nativeElement.options;
	}

	/** Gets/sets the multiple select state. */
	@Input({ transform: booleanAttribute })
	public set multiple(value: SelectComponentCustomElement['multiple']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.multiple = value;
		});
	}
	public get multiple(): SelectComponentCustomElement['multiple'] {
		return this.nativeElement.multiple;
	}

	/** Gets the open state of the dropdown. */
	@Input({ transform: booleanAttribute })
	public set open(value: SelectComponentCustomElement['open']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.open = value;
		});
	}
	public get open(): SelectComponentCustomElement['open'] {
		return this.nativeElement.open;
	}

	/** Sets the option builder callback that will be executed when building the option list in the dropdown. */
	@Input()
	public set optionBuilder(value: SelectComponentCustomElement['optionBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.optionBuilder = value;
		});
	}
	public get optionBuilder(): SelectComponentCustomElement['optionBuilder'] {
		return this.nativeElement.optionBuilder;
	}

	/** Sets the selected text builder callback that will be executed when getting the selected text to display in the field. */
	@Input()
	public set selectedTextBuilder(value: SelectComponentCustomElement['selectedTextBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.selectedTextBuilder = value;
		});
	}
	public get selectedTextBuilder(): SelectComponentCustomElement['selectedTextBuilder'] {
		return this.nativeElement.selectedTextBuilder;
	}

	/** Sets the callback to be executed when the user selects a value. */
	@Input()
	public set beforeValueChange(value: SelectComponentCustomElement['beforeValueChange']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.beforeValueChange = value;
		});
	}
	public get beforeValueChange(): SelectComponentCustomElement['beforeValueChange'] {
		return this.nativeElement.beforeValueChange;
	}

	/** Gets the popup element (when the dropdown is open). */
	public get popupElement(): SelectComponentCustomElement['popupElement'] {
		return this.nativeElement.popupElement;
	}

	/** Gets/sets the list of classes to apply to the popup element. */
	@Input()
	public set popupClasses(value: SelectComponentCustomElement['popupClasses']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.popupClasses = value;
		});
	}
	public get popupClasses(): SelectComponentCustomElement['popupClasses'] {
		return this.nativeElement.popupClasses;
	}

	/** Gets/sets the callback function for generating header content within the popup. */
	@Input()
	public set popupHeaderBuilder(value: SelectComponentCustomElement['popupHeaderBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.popupHeaderBuilder = value;
		});
	}
	public get popupHeaderBuilder(): SelectComponentCustomElement['popupHeaderBuilder'] {
		return this.nativeElement.popupHeaderBuilder;
	}

	/** Gets/sets the callback function for generating header content within the popup. */
	@Input()
	public set popupFooterBuilder(value: SelectComponentCustomElement['popupFooterBuilder']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.popupFooterBuilder = value;
		});
	}
	public get popupFooterBuilder(): SelectComponentCustomElement['popupFooterBuilder'] {
		return this.nativeElement.popupFooterBuilder;
	}

	/** Gets/sets whether the popup width is synchronized with the popup target width. */
	@Input({ transform: booleanAttribute })
	public set syncPopupWidth(value: SelectComponentCustomElement['syncPopupWidth']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.syncPopupWidth = value;
		});
	}
	public get syncPopupWidth(): SelectComponentCustomElement['syncPopupWidth'] {
		return this.nativeElement.syncPopupWidth;
	}

	/** Gets/sets the maximum number of options to display in the dropdown. */
	@Input({ transform: numberAttribute })
	public set optionLimit(value: SelectComponentCustomElement['optionLimit']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.optionLimit = value;
		});
	}
	public get optionLimit(): SelectComponentCustomElement['optionLimit'] {
		return this.nativeElement.optionLimit;
	}

	/** Controls the observation of scroll events on the dropdown. */
	@Input({ transform: booleanAttribute })
	public set observeScroll(value: SelectComponentCustomElement['observeScroll']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.observeScroll = value;
		});
	}
	public get observeScroll(): SelectComponentCustomElement['observeScroll'] {
		return this.nativeElement.observeScroll;
	}

	/** The number of pixels from the bottom to trigger the scroll bottom event. Only applicable if `observeScroll` is true. */
	@Input({ transform: numberAttribute })
	public set observeScrollThreshold(value: SelectComponentCustomElement['observeScrollThreshold']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.observeScrollThreshold = value;
		});
	}
	public get observeScrollThreshold(): SelectComponentCustomElement['observeScrollThreshold'] {
		return this.nativeElement.observeScrollThreshold;
	}

	/** Gets/sets whether the popup width will be constrained to a max width of the viewport width (default: `100vw`). */
	@Input({ transform: booleanAttribute })
	public set constrainPopupWidth(value: SelectComponentCustomElement['constrainPopupWidth']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.constrainPopupWidth = value;
		});
	}
	public get constrainPopupWidth(): SelectComponentCustomElement['constrainPopupWidth'] {
		return this.nativeElement.constrainPopupWidth;
	}

	/**
	 * Gets/sets whether the options will wrap their text or not.
	 * This only applies if `constrainPopupWidth` is `true`, if there is an explicit width set via CSS.
	 */
	@Input({ transform: booleanAttribute })
	public set wrapOptionText(value: SelectComponentCustomElement['wrapOptionText']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.wrapOptionText = value;
		});
	}
	public get wrapOptionText(): SelectComponentCustomElement['wrapOptionText'] {
		return this.nativeElement.wrapOptionText;
	}


	public appendOptions(...args: Parameters<SelectComponentCustomElement['appendOptions']>): ReturnType<SelectComponentCustomElement['appendOptions']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.appendOptions(...args));
	}


	public selectAll(...args: Parameters<SelectComponentCustomElement['selectAll']>): ReturnType<SelectComponentCustomElement['selectAll']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.selectAll(...args));
	}


	public deselectAll(...args: Parameters<SelectComponentCustomElement['deselectAll']>): ReturnType<SelectComponentCustomElement['deselectAll']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.deselectAll(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<SelectComponentCustomElement>,
		protected zone: NgZone
	) {
		defineSelectComponent();
		changeDetectorRef.detach();
	}
}
