// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { SwitchComponent as SwitchComponentCustomElement } from '@tylertech/forge';

/** The custom element class behind the `<forge-switch>` element. */
@Component({
  selector: 'forge-switch',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class SwitchComponent {


	@Input()
	public set dense(value: SwitchComponentCustomElement['dense'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.dense = value != null && `${value}` !== 'false';
		});
	}

	public get dense(): SwitchComponentCustomElement['dense'] {
		return this.elementRef.nativeElement.dense;
	}


	@Input()
	public set disabled(value: SwitchComponentCustomElement['disabled'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabled = value != null && `${value}` !== 'false';
		});
	}

	public get disabled(): SwitchComponentCustomElement['disabled'] {
		return this.elementRef.nativeElement.disabled;
	}


	@Input()
	public set selected(value: SwitchComponentCustomElement['selected'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.selected = value != null && `${value}` !== 'false';
		});
	}

	public get selected(): SwitchComponentCustomElement['selected'] {
		return this.elementRef.nativeElement.selected;
	}


	@Input()
	public set labelPosition(value: SwitchComponentCustomElement['labelPosition']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.labelPosition = value;
		});
	}

	public get labelPosition(): SwitchComponentCustomElement['labelPosition'] {
		return this.elementRef.nativeElement.labelPosition;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<SwitchComponentCustomElement>,
		protected zone: NgZone
	) {
		if (!window.customElements.get('forge-switch')) {
			window.customElements.define('forge-switch', SwitchComponentCustomElement);
		}
		changeDetectorRef.detach();
	}
}
