// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { SwitchComponent as SwitchComponentCustomElement, defineSwitchComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-switch>` element. */
@Component({
  selector: 'forge-switch',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class SwitchComponent {

	/** The forge-switch element. */
	public readonly nativeElement = this.elementRef.nativeElement;


	@Input({ transform: booleanAttribute })
	public set dense(value: SwitchComponentCustomElement['dense']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.dense = value;
		});
	}
	public get dense(): SwitchComponentCustomElement['dense'] {
		return this.nativeElement.dense;
	}


	@Input({ transform: booleanAttribute })
	public set disabled(value: SwitchComponentCustomElement['disabled']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.disabled = value;
		});
	}
	public get disabled(): SwitchComponentCustomElement['disabled'] {
		return this.nativeElement.disabled;
	}


	@Input({ transform: booleanAttribute })
	public set selected(value: SwitchComponentCustomElement['selected']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.selected = value;
		});
	}
	public get selected(): SwitchComponentCustomElement['selected'] {
		return this.nativeElement.selected;
	}


	@Input()
	public set labelPosition(value: SwitchComponentCustomElement['labelPosition']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.labelPosition = value;
		});
	}
	public get labelPosition(): SwitchComponentCustomElement['labelPosition'] {
		return this.nativeElement.labelPosition;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<SwitchComponentCustomElement>,
		protected zone: NgZone
	) {
		defineSwitchComponent();
		changeDetectorRef.detach();
	}
}
