// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { ButtonAreaComponent as ButtonAreaComponentCustomElement, defineButtonAreaComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-button-area>` element. */
@Component({
  selector: 'forge-button-area',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class ButtonAreaComponent {

	/** Controls whether the component and associated button element are disabled. */
	@Input()
	public set disabled(value: ButtonAreaComponentCustomElement['disabled'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.disabled = value != null && `${value}` !== 'false';
		});
	}

	public get disabled(): ButtonAreaComponentCustomElement['disabled'] {
		return this.elementRef.nativeElement.disabled;
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<ButtonAreaComponentCustomElement>,
		protected zone: NgZone
	) {
		defineButtonAreaComponent();
		changeDetectorRef.detach();
	}
}
