// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input, inject } from '@angular/core';
import { ButtonAreaComponent as ButtonAreaComponentCustomElement, defineButtonAreaComponent } from '@tylertech/forge';

/**  */
@Component({
  selector: 'forge-button-area',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>',
  standalone: false
})
export class ButtonAreaComponent {
	protected elementRef = inject<ElementRef<ButtonAreaComponentCustomElement>>(ElementRef);
	protected zone = inject(NgZone);

	/** The forge-button-area element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Sets whether the button area and slotted button are disabled. Setting this on one will also set it on the other. */
	@Input({ transform: booleanAttribute })
	public set disabled(value: ButtonAreaComponentCustomElement['disabled']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.disabled = value;
		});
	}
	public get disabled(): ButtonAreaComponentCustomElement['disabled'] {
		return this.nativeElement.disabled;
	}

	constructor() {
		defineButtonAreaComponent();
		const changeDetectorRef = inject(ChangeDetectorRef);
		changeDetectorRef.detach();
	}
}
