// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { booleanAttribute, Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { RadioComponent as RadioComponentCustomElement, defineRadioComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-radio>` element. */
@Component({
  selector: 'forge-radio',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class RadioComponent {

	/** The forge-radio element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	/** Gets/sets whether the radio button is dense. */
	@Input({ transform: booleanAttribute })
	public set dense(value: RadioComponentCustomElement['dense']) {
		this.zone.runOutsideAngular(() => {
			this.nativeElement.dense = value;
		});
	}
	public get dense(): RadioComponentCustomElement['dense'] {
		return this.nativeElement.dense;
	}


	public syncCheckedState(...args: Parameters<RadioComponentCustomElement['syncCheckedState']>): ReturnType<RadioComponentCustomElement['syncCheckedState']> {
		return this.zone.runOutsideAngular(() => this.nativeElement.syncCheckedState(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<RadioComponentCustomElement>,
		protected zone: NgZone
	) {
		defineRadioComponent();
		changeDetectorRef.detach();
	}
}
