// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { DividerComponent as DividerComponentCustomElement, defineDividerComponent } from '@tylertech/forge';

/** The custom element class behind the `<forge-divider>` element. */
@Component({
  selector: 'forge-divider',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class DividerComponent {

	/** The forge-divider element. */
	public readonly nativeElement = this.elementRef.nativeElement;

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<DividerComponentCustomElement>,
		protected zone: NgZone
	) {
		defineDividerComponent();
		changeDetectorRef.detach();
	}
}
