// This code was generated by the angular-custom-elements-schematic.  Any changes will be overwritten next time it runs.
import { Component, ElementRef, ChangeDetectionStrategy, ChangeDetectorRef, NgZone, Input } from '@angular/core';
import { OpenIconComponent as OpenIconComponentCustomElement, defineOpenIconComponent } from '@tylertech/forge';

/** The web component class behind the `<forge-open-icon>` custom element. */
@Component({
  selector: 'forge-open-icon',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: '<ng-content></ng-content>'
})
export class OpenIconComponent {

	/** Controls the open state of the icon. */
	@Input()
	public set open(value: OpenIconComponentCustomElement['open'] | string) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.open = value != null && `${value}` !== 'false';
		});
	}

	public get open(): OpenIconComponentCustomElement['open'] {
		return this.elementRef.nativeElement.open;
	}

	/**
	 * Gets/sets the orientation of the icon.
	 * Valid values are 'vertical' (default) or 'horizontal'.
	 */
	@Input()
	public set orientation(value: OpenIconComponentCustomElement['orientation']) {
		this.zone.runOutsideAngular(() => {
			this.elementRef.nativeElement.orientation = value;
		});
	}

	public get orientation(): OpenIconComponentCustomElement['orientation'] {
		return this.elementRef.nativeElement.orientation;
	}


	public initializedCallback(...args: Parameters<OpenIconComponentCustomElement['initializedCallback']>): ReturnType<OpenIconComponentCustomElement['initializedCallback']> {
		return this.zone.runOutsideAngular(() => this.elementRef.nativeElement.initializedCallback(...args));
	}

	constructor(
		changeDetectorRef: ChangeDetectorRef,
		protected elementRef: ElementRef<OpenIconComponentCustomElement>,
		protected zone: NgZone
	) {
		defineOpenIconComponent();
		changeDetectorRef.detach();
	}
}
